import './App.css'
import Loader from './components/Loader'
import CustomCursor from './components/CustomCursor'
import MouseGlow from './components/MouseGlow'
import SmoothScroll from './components/SmoothScroll'
import ScrollAnimations from './components/ScrollAnimations'
import Hero from './components/Hero'
import About from './components/About'
import Skills from './components/Skills'
import FeaturedProject from './components/FeaturedProject'
import Projects from './components/Projects'
import Experience from './components/Experience'
import Stats from './components/Stats'
import Contact from './components/Contact'
import Footer from './components/Footer'

export default function App(){return <><Loader/><CustomCursor/><MouseGlow/><SmoothScroll/><ScrollAnimations/><main><Hero/><div className="ticker" aria-hidden="true"><div>REACT — NEXT.JS — NODE.JS — LARAVEL — AI INTEGRATION — REST APIs — REACT — NEXT.JS — NODE.JS — LARAVEL — AI INTEGRATION — REST APIs — </div></div><About/><Skills/><FeaturedProject/><Projects/><Experience/><Stats/><section className="statement"><p>Clean interfaces. Reliable systems.</p><h2>Ideas built to<br/><span>perform.</span></h2><span className="mark">RH</span></section><Contact/><Footer/></main></>}
